# TAG: kernel-basic
FROM parthibx24/aosp-dockerscripts:bare

# Essential build tools
RUN apt install -y gcc make
RUN apt install -y bc

# MTK DrvGen Requirements
RUN apt install -y libglib2.0-0 libgl1